### ISSUE TITLE
腾讯云报错： AuthFailure.SignatureFailure`

### ISSUE THREAD

**Issue by nkbai** [zjp-CN/bilingual#37]
错误信息：`The provided credentials could not be validated. Please check your signature is correct.`
错误含义：签名错误。签名计算错误，请对照调用方式中的签名方法文档检查签名计算过程。

我提供了腾讯云提供的SecretId和SecretKey，

![image](https://user-images.githubusercontent.com/10471399/215639236-fc49f96c-0f0e-44bc-8da3-84028de12a6d.png)

**Comment by nkbai** [comment]
发现原因是默认的配置文件没有读取，我用的是mac，文件路径：
~/.config/bilingual.toml，里面配置了，没用。

**Comment by zjp-CN** [comment]
`LOG=DEBUG bilingual -a tencent "hi"` 能看到配置文件吗，我在 linux 下也使用 `~/.config/bilingual.toml` 配置文件，打印

```
只列出重点
10:39:04 [DEBUG] (1) bilingual::cmd: Bilingual {
    api: Tencent,
    toml: "/root/.config/bilingual.toml",
    multiquery: [
        "hi",
    ],
}
Config {
    api: Tencent,
    tencent: Some(
        User {
            id: "xxx",
            key: "xxx",
            region: Beijing,
            projectid: 0,
            qps: 5,
            limit: Char(
                2000,
            ),
        },
    ),
}
```

**Comment by nkbai** [comment]
```
[INFO] log-level: term => DEBUG, file => DEBUG; log-file => bilingual.log
17:17:53 [DEBUG] (1) bilingual::cmd: Bilingual {
    api: Tencent,
    id: "",
    key: "",
    from: "en",
    to: "zh",
    singlequery: "",
    input_files: [],
    input_dirs: [],
    output_files: [],
    output_dirs: [],
    replace_file: false,
    forbid_dir_creation: false,
    toml: "~/.config/bilingual.toml",
    multiquery: [
        "hi",
    ],
}
17:17:53 [DEBUG] (1) bilingual:
Config {
    src: Src {
        from: "en",
        to: "zh",
        query: "hi",
        dir_file: DirFile {
            dir: Some(
                DirBuilder {
                    inner: DirBuilder {
                        mode: 511,
                    },
                    recursive: true,
                },
            ),
            replace_file: false,
        },
        input_files: [],
        input_dirs: [],
        output_files: [],
        output_dirs: [],
    },
    api: Tencent,
    baidu: None,
    tencent: Some(
        User {
            id: "",
            key: "",
            region: Beijing,
            projectid: 0,
            qps: 5,
            limit: Char(
                2000,
            ),
        },
    ),
    niutrans: None,
}
17:17:53 [DEBUG] (1) bilingual::config:
q = ["hi"]
17:17:53 [DEBUG] (2) reqwest::connect: starting new connection: https://tmt.tencentcloudapi.com/
17:17:53 [DEBUG] (1) bilingual::config:
q = ["hi"]
query = Query {
    from: "en",
    to: "zh",
    projectid: 0,
    q: [
        "hi",
    ],
}
header = Header {
    datetime: 2023-01-31 9:17:53.478324 +00:00:00,
    timestamp: "1675156673",
    credential_scope: "2023-01-31/tmt/tc3_request",
    authorization: "TC3-HMAC-SHA256 Credential=/2023-01-31/tmt/tc3_request, SignedHeaders=content-type;host, Signature=69a5d4aac00e0775c8200bbb8cbaadc23e885872b4d142469f8e7d5020582c99",
    user: User {
        id: "",
        key: "",
        region: Beijing,
        projectid: 0,
        qps: 5,
        limit: Char(
            2000,
        ),
    },
    query: Query {
        from: "en",
        to: "zh",
        projectid: 0,
        q: [
            "hi",
        ],
    },
}
bytes = b"{\"Response\":{\"Error\":{\"Code\":\"AuthFailure.SignatureFailure\",\"Message\":\"The provided credentials could not be validated. Please check your signature is correct.\"},\"RequestId\":\"fc6aaaf8-2140-4b4f-84b0-41f37351d96f\"}}"
17:17:53 [DEBUG] (1) bilingual::config: iter = [
    Response {
        res: Err {
            id: "fc6aaaf8-2140-4b4f-84b0-41f37351d96f",
            error: ResponseError {
                code: "AuthFailure.SignatureFailure",
                msg: "The provided credentials could not be validated. Please check your signature is correct.",
            },
        },
    },
]
17:17:53 [DEBUG] (1) bilingual::md: event: Start(Paragraph)
17:17:53 [DEBUG] (1) bilingual::md: event: Text(Borrowed("hi"))
17:17:53 [DEBUG] (1) bilingual::md: event: End(Paragraph)
[ERROR] 错误码：`AuthFailure.SignatureFailure`
错误信息：`The provided credentials could not be validated. Please check your signature is correct.`
错误含义：签名错误。签名计算错误，请对照调用方式中的签名方法文档检查签名计算过程。
以上内容由腾讯云 API 返回
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/bai/.cargo/registry/src/github.com-1ecc6299db9ec823/bilingual-0.1.1/src/config.rs:428:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```


配置文件：
```
❯ ls -lh ~/.config/bilingual.toml
-rw-r--r--  1 bai  staff   188B Jan 31 09:55 /Users/bai/.config/bilingual.toml
```

**Comment by zjp-CN** [comment]
我记起来了，腾讯云要配置一下。
* 创建子账号
![image](https://user-images.githubusercontent.com/25300418/215789556-17fce1e1-75df-4974-94e5-6b569c15e135.png)
* 对子账号关联策略
![image](https://user-images.githubusercontent.com/25300418/215789919-f5f4d129-8c1d-4b66-89fc-c75967909f58.png)

**Comment by nkbai** [comment]
我已经配置了，通过 -i -k 指定就可以工作，但是通过配置文件就不行

**Comment by nkbai** [comment]
```
❯ bilingual -a tencent "# 标题" "正文：模拟 markdown 文件的内容。" -f zh -t en --toml ~/.config/bilingual.toml
# 标题

# Title

正文：模拟 markdown 文件的内容。

Body: simulates the contents of the markdown file.

Downloads/pbd on  main [✘!?]
❯ bilingual -a tencent "# 标题" "正文：模拟 markdown 文件的内容。" -f zh -t en
[ERROR] 错误码：`AuthFailure.SignatureFailure`
错误信息：`The provided credentials could not be validated. Please check your signature is correct.`
错误含义：签名错误。签名计算错误，请对照调用方式中的签名方法文档检查签名计算过程。
以上内容由腾讯云 API 返回
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/bai/.cargo/registry/src/github.com-1ecc6299db9ec823/bilingual-0.1.1/src/config.rs:428:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Downloads/pbd on  main [✘!?]
❯ ls
total 29760
-rw-r--r--@   1 bai  staff  6789273 Jan 30 19:29 aaa.docx
drwxr-xr-x    3 bai  staff       96 Jan 30 19:30 images
-rw-r--r--@   1 bai  staff   858188 Jan 30 20:06 aaa.md
-rw-r--r--@   1 bai  staff   858188 Jan 31 10:05 bbb.md
drwxr-xr-x    8 bai  staff      256 Feb  1 11:25 .
-rw-r--r--    1 bai  staff  6719092 Feb  1 11:25 bilingual.log.first
drwx------@ 540 bai  staff    17280 Feb  1 11:46 ..
-rw-r--r--    1 bai  staff      407 Feb  1 13:43 bilingual.log

```
明确指定可以，用默认路径不可以，感觉是个bug。

**Comment by nkbai** [comment]
在mac上，默认路径不是~/.config,而是/Users/xxx/Library/Application Support/

**Comment by zjp-CN** [comment]
好吧。。。这个依赖于 OS 的路径我需要使用 https://docs.rs/dirs/latest/dirs/fn.config_dir.html

谢谢反馈

**Comment by zjp-CN** [comment]
把  ~/.config 下的 bilingual.toml 移至 Mac 的那个路径，应该可以工作吧。因为我发现代码目前就是用的那个函数 ：）

**Comment by nkbai** [comment]
不可以，
```
❯ bilingual -a tencent "# 标题" "正文：模拟 markdown 文件的内容。" -f zh -t en
[ERROR] 错误码：`AuthFailure.SignatureFailure`
错误信息：`The provided credentials could not be validated. Please check your signature is correct.`
错误含义：签名错误。签名计算错误，请对照调用方式中的签名方法文档检查签名计算过程。
以上内容由腾讯云 API 返回
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/bai/.cargo/registry/src/github.com-1ecc6299db9ec823/bilingual-0.1.1/src/config.rs:428:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
我一会儿调试一下吧，看看啥bug，

**Comment by zjp-CN** [comment]
我这也复现了，遇到和你一样的错误，我正在查看

**Comment by zjp-CN** [comment]
你使用我的最新的 main 分支 （即 40f1dc8641b27838962548cf56a6621225c92514 及其之后的提交），`TERM_LOG=debug cargo r -- -a tencent "hi"` 本地编译运行，打印的结果是什么？如果配置文件未读到，也没提供其他途径（命令行参数、环境变量）的配置，会显示

```
20:41:32 [DEBUG] (1) bilingual::config: "/root/.config/bilingual.toml" 配置文件不存在
20:41:32 [DEBUG] (1) bilingual::cmd: 由于未找到配置文件，先使用默认配置（无 id 和 key）
Error: id 不应该为空
```

提供命令行参数则显示

```
20:45:11 [DEBUG] (1) bilingual::config: "/root/.config/bilingual.toml" 配置文件不存在
20:45:11 [DEBUG] (1) bilingual::cmd: 由于未找到配置文件，先使用默认配置（无 id 和 key）
20:45:11 [DEBUG] (1) bilingual::cmd: id 被命令行参数覆盖
20:45:11 [DEBUG] (1) bilingual::cmd: key 被命令行参数覆盖
```

正常读到当前目录下的 bilingual.toml 或者全局目录下的 bilingual.toml 则不会显示这些。

**Comment by zjp-CN** [comment]
> 我这也复现了，遇到和你一样的错误

我复现的原因是我把 ~/.config/bilingual.toml 给移除了 。实际我这边正常能读到全局配置。
